
// Random C Code generated by AI Assistant

#include <stdio.h>

int main() {
  int age = 25;
  char name[30];
  printf("Enter your name: ");
  scanf("%s", name);
  printf("Hello, %s! You are %d years old.", name, age);
  return 0;
}